### ISSUE TITLE
Errors during installation

### ISSUE THREAD

**Issue by roschler** [Microsoft/TextWorld#116]
I followed the readme instructions to install TextWorld.  When I execute the command on my Ubuntu 18.04 box with Python3 3.6.7 installed and PIP installed too:

`pip install .`

I get the error output below.  How do I fix this?
```
  Running setup.py install for textworld ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-cNatrJ-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-8h1DWH-record/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    running install
    Running post install task
    + echo 'Running setup.sh...'
    Running setup.sh...
    ++ uname -s
    + unameOut=Linux
    + case "${unameOut}" in
    + machine=Linux
    + tatsu textworld/logic/logic.ebnf -o textworld/logic/parser.py -G textworld/logic/model.py
    ./setup.sh: line 19: tatsu: command not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-cNatrJ-build/setup.py", line 67, in <module>
        'nose==1.3.7',
      File "/usr/lib/python2.7/dist-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-cNatrJ-build/setup.py", line 24, in run
        msg="Running post install task")
      File "/usr/lib/python2.7/distutils/cmd.py", line 349, in execute
        util.execute(func, args, msg, dry_run=self.dry_run)
      File "/usr/lib/python2.7/distutils/util.py", line 309, in execute
        func(*args)
      File "/tmp/pip-cNatrJ-build/setup.py", line 18, in _pre_install
        check_call(['./setup.sh'], shell=True, cwd=os.getcwd())
      File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['./setup.sh']' returned non-zero exit status 127
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-cNatrJ-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-8h1DWH-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-cNatrJ-build/
```

**Comment by tavianator** [comment]
You'll have to install `tatsu` first, and make sure it's on your PATH.  Pip should have done that for you but it doesn't work in all configurations.

**Comment by MarcCote** [comment]
Do we even really need those two Tatsu lines? We are shipping the `model.py` and `parser.py` files after all.

**Comment by tavianator** [comment]
Yeah not really, no reason to make users run `tatsu` to generate some files that are already there.
