### ISSUE TITLE
Install errors with PyPI version of TextWorld

### ISSUE THREAD

**Issue by leonoverweel** [Microsoft/TextWorld#121]
I followed the README.md instructions for installing TextWorld from PyPI in a clean environment, and I'm getting a build issue when pip tries to build textworld.

To replicate in a clean Conda environment on macOS:

```bash
brew install libffi curl git
conda create --name textworld python=3.7
conda activate textworld
pip install textworld
```

This fails with the following error:

```
Successfully built pyyaml urwid hashids jericho pybars3 greenlet gevent gym PyMeta3 future
Failed to build textworld
Installing collected packages: numpy, tqdm, pycparser, cffi, decorator, networkx, pyyaml, urwid, six, more-itertools, tatsu, hashids, jericho, PyMeta3, pybars3, itsdangerous, Werkzeug, MarkupSafe, Jinja2, click, flask, urllib3, selenium, greenlet, gevent, pillow, pyparsing, pydot, wcwidth, prompt-toolkit, idna, chardet, requests, future, pyglet, gym, textworld
  Running setup.py install for textworld ... error
    Complete output from command /Users/leon/miniconda3/envs/textworld/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/8r/mj5p4vvj4wj1dbl7bz7gj1hc0000gn/T/pip-install-1qx6q992/textworld/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/8r/mj5p4vvj4wj1dbl7bz7gj1hc0000gn/T/pip-record-egmjy2z6/install-record.txt --single-version-externally-managed --compile:
    running install
    Running post install task
    + echo 'Running setup.sh...'
    Running setup.sh...
    ++ uname -s
    + unameOut=Darwin
    + case "${unameOut}" in
    + machine=Mac
    + tatsu textworld/logic/logic.ebnf -o textworld/logic/parser.py -G textworld/logic/model.py
    ------------------------------------------------------------------------
             284  lines in grammar
              44  rules in grammar
             300  nodes in AST
    + tatsu textworld/textgen/textgen.ebnf -o textworld/textgen/parser.py -G textworld/textgen/model.py
    ------------------------------------------------------------------------
              59  lines in grammar
               9  rules in grammar
              46  nodes in AST
    + cd textworld/thirdparty/
    + '[' '!' -e I7_6M62_Linux_all.tar.gz ']'
    + '[' '!' -d inform7-6M62 ']'
    + echo 'Installing Inform7 CLI'
    Installing Inform7 CLI
    + cd inform7-6M62/
    + ./install-inform7.sh --prefix /private/var/folders/8r/mj5p4vvj4wj1dbl7bz7gj1hc0000gn/T/pip-install-1qx6q992/textworld/textworld/thirdparty/inform7-6M62
    ./setup.sh: line 39: ./install-inform7.sh: No such file or directory
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/8r/mj5p4vvj4wj1dbl7bz7gj1hc0000gn/T/pip-install-1qx6q992/textworld/setup.py", line 67, in <module>
        'nose==1.3.7',
      File "/Users/leon/miniconda3/envs/textworld/lib/python3.7/site-packages/setuptools/__init__.py", line 143, in setup
        return distutils.core.setup(**attrs)
      File "/Users/leon/miniconda3/envs/textworld/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Users/leon/miniconda3/envs/textworld/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/Users/leon/miniconda3/envs/textworld/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/private/var/folders/8r/mj5p4vvj4wj1dbl7bz7gj1hc0000gn/T/pip-install-1qx6q992/textworld/setup.py", line 24, in run
        msg="Running post install task")
      File "/Users/leon/miniconda3/envs/textworld/lib/python3.7/distutils/cmd.py", line 335, in execute
        util.execute(func, args, msg, dry_run=self.dry_run)
      File "/Users/leon/miniconda3/envs/textworld/lib/python3.7/distutils/util.py", line 286, in execute
        func(*args)
      File "/private/var/folders/8r/mj5p4vvj4wj1dbl7bz7gj1hc0000gn/T/pip-install-1qx6q992/textworld/setup.py", line 18, in _pre_install
        check_call(['./setup.sh'], shell=True, cwd=os.getcwd())
      File "/Users/leon/miniconda3/envs/textworld/lib/python3.7/subprocess.py", line 347, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['./setup.sh']' returned non-zero exit status 1.
    
    ----------------------------------------
Command "/Users/leon/miniconda3/envs/textworld/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/8r/mj5p4vvj4wj1dbl7bz7gj1hc0000gn/T/pip-install-1qx6q992/textworld/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/8r/mj5p4vvj4wj1dbl7bz7gj1hc0000gn/T/pip-record-egmjy2z6/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/8r/mj5p4vvj4wj1dbl7bz7gj1hc0000gn/T/pip-install-1qx6q992/textworld/
```

It looks like this is the same issue as in #116, which got resolved in #118 (on Jan 25th). The [package on PyPI](https://pypi.org/project/textworld/#history) was last updated on Jan 8th, so I think this could be fixed by updating the code on PyPI.

**Comment by MarcCote** [comment]
Hi @leonoverweel. The error you got is actually different from #116. In #116 The reason why setup.sh failed was `./setup.sh: line 19: tatsu: command not found` whereas in your case it seems to be `./setup.sh: line 39: ./install-inform7.sh: No such file or directory`.

It seems some of the lines in setup.sh are not evaluated correctly
```
    + '[' '!' -e I7_6M62_Linux_all.tar.gz ']'
    + '[' '!' -d inform7-6M62 ']'
```
From the transcript, I see you are using a Mac, what shell are you using?

@tavianator can you have a look at this error.

**Comment by leonoverweel** [comment]
Hi Marc, thanks for catching that. I’m using the default terminal on macOS Mojave (10.14.2). Thanks for the quick reply!

**Comment by tavianator** [comment]
Any chance the download of `I7_6M62_Linux_all.tar.gz` failed or was corrupted?  Does yours match this?

```
$ sha256sum ./textworld/thirdparty/I7_6M62_Linux_all.tar.gz
684e33d37e6fd21a1822233ddf35937f3a365c4a366486a113c5f32015d93cbd  ./textworld/thirdparty/I7_6M62_Linux_all.tar.gz
```

**Comment by tavianator** [comment]
Okay never mind, I see what's happening.  The published package includes the `textworld/thirdparty/inform7-6M62` directory, but it's incomplete.  So the script sees that it already exists and doesn't extract anything, but it's missing the `install-inform7.sh` script, hence the error.  We need to fix this in `MANIFEST.in`.

**Comment by MarcCote** [comment]
The `frotz` folder shouldn't be there either. In `MANIFEST.in` I had to include those folders otherwise they wouldn't be installed with `pip install`.

**Comment by ai-nikolai** [comment]
`pip3 install --use-pep517 textworld` the following worked for me on MacBookPro M2
