### ISSUE TITLE
Installation error due missing third-party library

### ISSUE THREAD

**Issue by brenocarvalho** [microsoft/TextWorld#170]
Hi, I have a macOS 10.13.6 and I run into an error during the README.md installation steps.

I tried the steps:
```
brew install libffi curl git
conda create --name textworld python=3.7
conda activate textworld
pip install textworld
```

After it failed, I tried the following (as suggested in one of the replies of issue #130):

```
pip install https://github.com/Microsoft/TextWorld/archive/master.zip
```

Which entailed to the same error message. 
I also tried to install previous commits that I was able to install before and got the same message.

I show the error message at the end of this message, and highlight here the fragment that I believe to be causing this error:

```
...

    + cd textworld/thirdparty/
    + '[' '!' -e I7_6M62_Linux_all.tar.gz ']'
    + '[' '!' -d inform7-6M62 ']'
    + tar xf I7_6M62_Linux_all.tar.gz
    tar: Unrecognized archive format
    tar: Error exit delayed from previous errors.
...
```

*The part of the error message that I highlighted leads me to believe that the problem is that the _setup.sh_ was not able to download the file _I7_6M62_Linux_all.tar.gz_. I checked the link ( http://inform7.com/download/content/6M62/I7_6M62_Linux_all.tar.gz ) and, indeed, the link is broken. I went to the repository page of inform7 (https://aur.archlinux.org/packages/inform7/ ) and the repository seems to be gone.*

_I also read some other installation issues, like #116 and none of the above seems to address this problem_

**Any thoughts on that issue?**

Just in case I missed something, there it is the entire error message:
```
Building wheels for collected packages: textworld
  Building wheel for textworld (setup.py) ... error
  ERROR: Complete output from command /Users/brenow/miniconda3/envs/textworld/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/vz/hyt4bd3s7fl16jf_8dqf_l6c0000gn/T/pip-install-_uhqip78/textworld/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/vz/hyt4bd3s7fl16jf_8dqf_l6c0000gn/T/pip-wheel-i8i4tolc --python-tag cp37:
  ERROR: running bdist_wheel
  running build
  running build_py
  + echo 'Running setup.sh...'
  Running setup.sh...
  ++ uname -s
  + unameOut=Darwin
  + case "${unameOut}" in
  + machine=Mac
  + cd textworld/thirdparty/
  + '[' '!' -e I7_6M62_Linux_all.tar.gz ']'
  + echo 'Downloading Inform7 CLI'
  Downloading Inform7 CLI
  + curl -LO http://inform7.com/download/content/6M62/I7_6M62_Linux_all.tar.gz
    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                   Dload  Upload   Total   Spent    Left  Speed
  100   363  100   363    0     0   1143      0 --:--:-- --:--:-- --:--:--  1145
  + '[' Mac == Mac ']'
  + '[' '!' -e I7-6M62-OSX.dmg ']'
  + echo 'Downloading Inform7 for Mac'
  Downloading Inform7 for Mac
  + curl -LO http://inform7.com/download/content/6M62/I7-6M62-OSX.dmg
    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                   Dload  Upload   Total   Spent    Left  Speed
  100   354  100   354    0     0   1175      0 --:--:-- --:--:-- --:--:--  1172
  + '[' '!' -d inform7-6M62 ']'
  + tar xf I7_6M62_Linux_all.tar.gz
  tar: Unrecognized archive format
  tar: Error exit delayed from previous errors.
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/vz/hyt4bd3s7fl16jf_8dqf_l6c0000gn/T/pip-install-_uhqip78/textworld/setup.py", line 67, in <module>
      'nose==1.3.7',
    File "/Users/brenow/miniconda3/envs/textworld/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/Users/brenow/miniconda3/envs/textworld/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/Users/brenow/miniconda3/envs/textworld/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/Users/brenow/miniconda3/envs/textworld/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/Users/brenow/miniconda3/envs/textworld/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 192, in run
      self.run_command('build')
    File "/Users/brenow/miniconda3/envs/textworld/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/Users/brenow/miniconda3/envs/textworld/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/Users/brenow/miniconda3/envs/textworld/lib/python3.7/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/Users/brenow/miniconda3/envs/textworld/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/Users/brenow/miniconda3/envs/textworld/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/private/var/folders/vz/hyt4bd3s7fl16jf_8dqf_l6c0000gn/T/pip-install-_uhqip78/textworld/setup.py", line 37, in run
      _pre_install(None)
    File "/private/var/folders/vz/hyt4bd3s7fl16jf_8dqf_l6c0000gn/T/pip-install-_uhqip78/textworld/setup.py", line 18, in _pre_install
      check_call(['./setup.sh'], shell=True, cwd=os.getcwd())
    File "/Users/brenow/miniconda3/envs/textworld/lib/python3.7/subprocess.py", line 347, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['./setup.sh']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for textworld
  Running setup.py clean for textworld
Failed to build textworld
Installing collected packages: textworld
  Running setup.py install for textworld ... error
    ERROR: Complete output from command /Users/brenow/miniconda3/envs/textworld/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/vz/hyt4bd3s7fl16jf_8dqf_l6c0000gn/T/pip-install-_uhqip78/textworld/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/vz/hyt4bd3s7fl16jf_8dqf_l6c0000gn/T/pip-record-z70svmvj/install-record.txt --single-version-externally-managed --compile:
    ERROR: running install
    Running post install task
    + echo 'Running setup.sh...'
    Running setup.sh...
    ++ uname -s
    + unameOut=Darwin
    + case "${unameOut}" in
    + machine=Mac
    + cd textworld/thirdparty/
    + '[' '!' -e I7_6M62_Linux_all.tar.gz ']'
    + '[' '!' -d inform7-6M62 ']'
    + tar xf I7_6M62_Linux_all.tar.gz
    tar: Unrecognized archive format
    tar: Error exit delayed from previous errors.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/vz/hyt4bd3s7fl16jf_8dqf_l6c0000gn/T/pip-install-_uhqip78/textworld/setup.py", line 67, in <module>
        'nose==1.3.7',
      File "/Users/brenow/miniconda3/envs/textworld/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/Users/brenow/miniconda3/envs/textworld/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Users/brenow/miniconda3/envs/textworld/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/Users/brenow/miniconda3/envs/textworld/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/private/var/folders/vz/hyt4bd3s7fl16jf_8dqf_l6c0000gn/T/pip-install-_uhqip78/textworld/setup.py", line 24, in run
        msg="Running post install task")
      File "/Users/brenow/miniconda3/envs/textworld/lib/python3.7/distutils/cmd.py", line 335, in execute
        util.execute(func, args, msg, dry_run=self.dry_run)
      File "/Users/brenow/miniconda3/envs/textworld/lib/python3.7/distutils/util.py", line 291, in execute
        func(*args)
      File "/private/var/folders/vz/hyt4bd3s7fl16jf_8dqf_l6c0000gn/T/pip-install-_uhqip78/textworld/setup.py", line 18, in _pre_install
        check_call(['./setup.sh'], shell=True, cwd=os.getcwd())
      File "/Users/brenow/miniconda3/envs/textworld/lib/python3.7/subprocess.py", line 347, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['./setup.sh']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command "/Users/brenow/miniconda3/envs/textworld/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/vz/hyt4bd3s7fl16jf_8dqf_l6c0000gn/T/pip-install-_uhqip78/textworld/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/vz/hyt4bd3s7fl16jf_8dqf_l6c0000gn/T/pip-record-z70svmvj/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/vz/hyt4bd3s7fl16jf_8dqf_l6c0000gn/T/pip-install-_uhqip78/textworld/

```

**Comment by brenocarvalho** [comment]
Indeed, I download the inform7 files and put them in the `textworld/thirdparty` folder, and the installation proceeded successfully. The links I used to the files are the following:

**I7_6M62_Linux_all.tar.gz:** http://inform7.com/apps/6M62/I7_6M62_Linux_all.tar.gz
**I7-6M62-OSX.dmg:** https://www.ifarchive.org/if-archive/infocom/compilers/inform7/executables/I7_6M62_OSX.dmg

**Comment by MarcCote** [comment]
Indeed the Inform7 has been refactored. We are going to update the URL. Thanks for reporting this issue
