### ISSUE TITLE
pybars dependency

### ISSUE THREAD

**Issue by spMohanty** [Microsoft/TextWorld#27]
I consistently find this issue on python3.6 on both osx and linux when trying to use `tw-make`: 
```
mohanty@cluster9654:/tmp$ tw-make custom --world-size 5 --nb-objects 10 --quest-length 5 --output gen_games/
Traceback (most recent call last):
  File "/home/mohanty/anaconda3/bin/tw-make", line 10, in <module>
    import textworld
  File "/home/mohanty/anaconda3/lib/python3.6/site-packages/textworld/__init__.py", line 9, in <module>
    from textworld.generator import Game, GameMaker
  File "/home/mohanty/anaconda3/lib/python3.6/site-packages/textworld/generator/__init__.py", line 26, in <module>
    from textworld.generator.maker import GameMaker
  File "/home/mohanty/anaconda3/lib/python3.6/site-packages/textworld/generator/maker.py", line 24, in <module>
    from textworld.render import visualize
  File "/home/mohanty/anaconda3/lib/python3.6/site-packages/textworld/render/__init__.py", line 6, in <module>
    from textworld.render.serve import get_html_template
  File "/home/mohanty/anaconda3/lib/python3.6/site-packages/textworld/render/serve.py", line 23, in <module>
    import pybars
ModuleNotFoundError: No module named 'pybars'
mohanty@cluster9654:/tmp$ pip install pybars
Collecting pybars
  Downloading https://files.pythonhosted.org/packages/67/84/e61926cdb9f17576e69a7cf5a505be7dcf479765a821d95449f5d1f4b08a/pybars-0.0.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ql1njnsw/pybars/setup.py", line 22, in <module>
        description = file(
    NameError: name 'file' is not defined

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ql1njnsw/pybars/
You are using pip version 9.0.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
mohanty@cluster9654:/tmp$
```

**Comment by MarcCote** [comment]
With Python3, **pybars3** needs to be installed. That said, with the default TextWorld installation `tw-make` shouldn't require web and visualization libraries. We will fix it, thanks.

PS: you can install all [TextWorld's extras](https://github.com/Microsoft/TextWorld#extras) with `pip install .[prompt,vis]`
