### ISSUE TITLE
Problem on running play_generated_games.py script

### ISSUE THREAD

**Issue by ilkerkesen** [Microsoft/TextWorld#46]
Hi,

I use the current master's play_generated_games.py script and it fails as follows,

```
(textworld)  % python play_generated_games.py                                                                                                            ilkerkesen/ajan-metin (master ⚡) raftel
Random seed: 38653
Traceback (most recent call last):
  File "play_generated_games.py", line 135, in <module>
    main()
  File "play_generated_games.py", line 99, in main
    seed=game_seed, games_dir=args.output)
  File "/home/ilker/.conda/envs/textworld/lib/python3.7/site-packages/textworld/helpers.py", line 140, in make
    game = make_game(world_size, nb_objects, quest_length, grammar_flags)
  File "/home/ilker/.conda/envs/textworld/lib/python3.7/site-packages/textworld/generator/__init__.py", line 175, in make_game
    world = make_world(world_size, nb_objects=0, rngs=rngs)
  File "/home/ilker/.conda/envs/textworld/lib/python3.7/site-packages/textworld/generator/__init__.py", line 91, in make_world
    map_ = make_map(n_rooms=world_size, rng=rngs['rng_map'])
  File "/home/ilker/.conda/envs/textworld/lib/python3.7/site-packages/textworld/generator/__init__.py", line 47, in make_map
    edge_size = int(np.ceil(np.sqrt(n_rooms + 1)))
TypeError: can only concatenate list (not "int") to list
```

**Comment by ilkerkesen** [comment]
I think this is the problem,

https://github.com/Microsoft/TextWorld/blob/master/scripts_dev/play_generated_games.py#L18

I believe it shouldn't include `nargs="+"`. Am I right?

**Comment by MarcCote** [comment]
Hi, thank for reporting this issue. I've made PR #47 to bring this script up-to-date. Alternatively, you could accomplish the same using the following two commands:
```
tw-make custom --output gen_games/ --seed 51987
tw-play ./gen_games/game_51987.ulx
```
chaining the seed number (and other script parameters)  as needed.

**Comment by MarcCote** [comment]
Yes, that was one of the issues but there are others.

**Comment by MarcCote** [comment]
Should be fixed now. Otherwise, feel free to reopen it.
